### ISSUE TITLE
Entrevista 

### ISSUE THREAD

**Issue by evelyn-santiago** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-e-n-a#1]
[Entrevista.pdf](https://github.com/user-attachments/files/16858625/Entrevista.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenas tardes compañera, obtuvieron el 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
